export type ALIAS = {
    [key: string]: string
}

export default {
    "js": "jsx",
    "javascript": "jsx",
    "sh": "bash",
    "zsh": "bash",
    "console": "batch",
    "adoc": "asciidoc",
    "cs": "csharp",
    "fs": "fsharp",
    "bat": "batch",
    "cmd": "batch",
    "hbs": "handlebars",
    "html.hbs": "handlebars",
    "html.handlebars": "handlebars",
    "mk": "makefile",
    "mak": "makefile",
    "md": "markdown",
    "mkdown": "markdown",
    "mkd": "markdown",
    "pl": "perl",
    "pm": "perl",
    "php3": "php",
    "php4": "php",
    "php5": "php",
    "php6": "php",
    "py": "python",
    "gyp": "python",
    "rb": "ruby",
    "gemspec": "ruby",
    "podspec": "ruby",
    "thor": "ruby",
    "irb": "ruby",
    "vbs": "visual-basic",
    "html": "markup",
    "xml": "markup",
    "rss": "markup",
    "atom": "markup",
    "xjb": "markup",
    "xsd": "markup",
    "xsl": "markup",
    "plist": "markup",
    "yml": "yaml",
    "YAML": "yaml",
    "jsp": "java"
} as ALIAS;
